### ISSUE TITLE
unpack compute_pcb_stats()

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/pipdm#1]
Hi @Aeilert 

Can you please move the `compute_pcb_stats()` from the pcndm package to this one ans start to unpack it. There is a lot going on in this function: Computing the gini coefficient, the median, the lorenz curve, etc.
It will be much cleaner and easier to test if each of these component is extracted in their own function:

- compute_gini

- compute_lorenz

- etc.

**Comment by Aeilert** [comment]
Moved to `wbpip`.
