### ISSUE TITLE
Make sure censoring rules are correct 

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/pipdm#113]
Right now WLD 2017 is not censored, but it should be? 

**EDIT:** Here is what is currently in PovcalNet. 

![image](https://user-images.githubusercontent.com/8194990/150816206-4b330ad0-0431-41a8-96cb-d8ba96d36e04.png)

**Comment by danielmahler** [comment]
WLD 2017 should not be censored

**Comment by Aeilert** [comment]
Yep. Sorry. That's a typo. Meant 2018.
