### ISSUE TITLE
Fix extrapolation of two surveys with different welfare types

### ISSUE THREAD

**Issue by randrescastaneda** [PIP-Technical-Team/pipdm#57]
hi @Aeilert , 

In the reference year table (i.e., interpolated-means table) we still have an issue with FSM. In short, we have for the same reference years two different extrapolations if there are surveys with different welfare types. I am still not sure, which is the right approach. Either using the one that is closest to the reference year even if it is not of the same welfare type than the rest of the series or using the survey that is further away from the reference year but with the same welfare type...  See the code below to replicate the problem. 

```r
library(data.table)
dt_path <- "//w1wbgencifs01/pip/pip_ingestion_pipeline/pc_data/output/estimations/interpolated-means.fst"
dt <- fst::read_fst(dt_path, 
                    as.data.table = TRUE)

dt[ country_code == "FSM" & reporting_year %in% c(1999, 2000, 2001), 
   c("cache_id", "reporting_year", "survey_acronym", "welfare_type") ]
```

Best,

**Comment by tonyfujs** [comment]
@randrescastaneda @Aeilert 
If I'm not mistaken, we should already have the answer to what should be the correct behavior in PovcalNet's codebase (or Daniel's decision tree diagram). Is that case not covered already?

**Comment by Aeilert** [comment]
Hi @randrescastaneda 

This looks like a result of the survey coverage bug that was fixed [here](https://github.com/PIP-Technical-Team/pipdm/pull/55/files), but which you reverted [here](https://github.com/PIP-Technical-Team/pipdm/commit/356d4fd317030aaa9af628b0325cf4d167d06f58#diff-2e4a75dd567ec5aaa38d357cb32c50de0dcb4d19809c9a5f9b194d7c9afd1267). 

Is there a reason you reverted the change (i.e. did it create other unforeseen problems?) .  Or was it a mistake? If you did not intend to revert the bug fix, then I think we should be good to go. The problem then lies in `db_create_lkup_table()` and not selection of surveys itself. 

best,
Aleksander

**Comment by randrescastaneda** [comment]
Hi @Aeilert , 

Thank you so much for clarifying. I reverted your changes unintentionally. I apologize for that. Let me try bringing them back again, and I'll let you know if things are fixed. I"ll close this for now. 

Thanks. 
Best,

**Comment by randrescastaneda** [comment]
Hi @Aeilert , 

Unfortunately, the issue of FSM remains. Yo could see it by using the same code that I sent you in the first message of this thread. Also, I just updated the master branch of the pipeline, so you can investigate. you could either use the debugging suggestions in the [targets manual](https://books.ropensci.org/targets/debugging.html), or you can investigate in the way that I usually do it on targets. 

1. Identify what **target** executes the function that you think is causing the problem. I guess the target you need  is `dt_ref_mean_pred` since it uses `db_create_ref_year_table()`  which calls `db_create_lkup_table()`. 
2. using the function `targets::tar_load()`  load all the inputs that `db_create_ref_year_table()` needs
3.Start the debugger on `db_create_ref_year_table()` 

Please, let me know if you have any question. 

Best,

**Comment by randrescastaneda** [comment]
Hi @Aeilert , 

Never mind. It seems to be working now... I re ran the pipeline and the error was gone... weird. 

Sorry for bothering you. 
Best,
